@echo off
REM Starts the model server (with NPC voices), waits for it to answer, then
REM launches the game.
REM
REM The exported .exe is only the game client. NPC replies are generated by
REM backend/gguf_server.py, which loads the Q4_K_M adapter models from
REM training/gguf_models/ -- roughly 5GB of weights that are deliberately NOT
REM packed into the executable -- and speaks them with the Piper voices in
REM backend/voices/. Without the server the campus still loads and is
REM walkable; the dialogue box just reports that it is offline.
REM
REM Run this from anywhere; paths below are resolved relative to this file.

setlocal
set "GAME_DIR=%~dp0.."
set "REPO_ROOT=%GAME_DIR%\..\.."
set "PYTHON=%REPO_ROOT%\.venv\Scripts\python.exe"
set "GAME_EXE=%REPO_ROOT%\SampleGame\build\CampusNPC.exe"
set "VOICES=%REPO_ROOT%\backend\voices"

if not exist "%PYTHON%" (
    echo [!] No virtualenv at %PYTHON%
    echo     Create it and install requirements.txt from the repo root first.
    pause
    exit /b 1
)

REM --- voices ---------------------------------------------------------------
REM Speech is optional at runtime, but without voice models the NPCs are
REM silently mute, which is easy to mistake for a bug. Fetch them once.
if not exist "%VOICES%\*.onnx" (
    echo No NPC voices found. Downloading them once, about 315 MB...
    "%PYTHON%" "%REPO_ROOT%\backend\fetch_voices.py"
    if errorlevel 1 (
        echo [!] Voice download failed. The demo will run without speech.
    )
)

REM --- game build -----------------------------------------------------------
REM Rebuild when the exe is missing, or older than any NPC script. This check
REM exists because it bit once already: speech was added to the game code but
REM the exe was not re-exported, so the demo launched a build that never asked
REM for audio even though the server was ready to provide it.
set "STALE=0"
if not exist "%GAME_EXE%" (
    set "STALE=1"
) else (
    powershell -NoProfile -Command ^
      "$exe = (Get-Item '%GAME_EXE%').LastWriteTime;" ^
      "$src = Get-ChildItem '%GAME_DIR%\Systems\NPC' -File | Where-Object { $_.LastWriteTime -gt $exe };" ^
      "if ($src) { exit 1 } else { exit 0 }"
    if errorlevel 1 set "STALE=1"
)
if "%STALE%"=="1" (
    echo Game build is missing or out of date. Rebuilding...
    call "%~dp0build.bat"
    if not exist "%GAME_EXE%" (
        echo [!] Build failed; see the output above.
        pause
        exit /b 1
    )
)

REM --- server -----------------------------------------------------------------
echo Starting model server...
pushd "%REPO_ROOT%"
start "NPC model server" "%PYTHON%" -m uvicorn backend.gguf_server:app --port 8000
popd

echo Waiting for the server to come up...
REM Startup builds PDM v2 reference features for all 8 archetypes and loads
REM and warms every voice (the first synthesis on a fresh voice costs ~2 s),
REM so expect roughly 10 seconds before the first health check answers.
set /a TRIES=0
:wait
set /a TRIES+=1
if %TRIES% gtr 90 (
    echo [!] Server did not respond after 90s. Launching anyway - NPCs will
    echo     report the connection failure in-game.
    goto launch
)
curl -s -o nul -m 2 http://127.0.0.1:8000/health
if errorlevel 1 (
    REM One-second pause. Not `timeout /t 1`: timeout refuses to run when
    REM stdin is not an interactive console ("Input redirection is not
    REM supported") and returns immediately, so launched from a shortcut or
    REM another tool the loop would burn all 90 tries in a few seconds and
    REM start the game before the server was up. ping works everywhere.
    ping -n 2 127.0.0.1 >nul
    goto wait
)
echo Server is up.

REM Say whether speech is actually on, rather than leaving a mute NPC to be
REM discovered in-game.
powershell -NoProfile -Command ^
  "$h = Invoke-RestMethod http://127.0.0.1:8000/health;" ^
  "if ($h.speech -and $h.voices.Count -gt 0) { Write-Host ('Speech: ON  (' + $h.voices.Count + ' voices)') }" ^
  "else { Write-Host 'Speech: OFF - NPCs will reply in text only. Run backend\fetch_voices.py to enable.' }"

:launch
start "" "%GAME_EXE%"
endlocal
