@echo off
REM Starts the model server, waits for it to answer, then launches the game.
REM
REM The exported .exe is only the game client. NPC replies are generated by
REM backend/gguf_server.py, which loads the Q4_K_M adapter models from
REM training/gguf_models/ -- roughly 5GB of weights that are deliberately NOT
REM packed into the executable. Without the server the campus still loads and
REM is walkable; the dialogue box just reports that it is offline.
REM
REM Run this from anywhere; paths below are resolved relative to this file.

setlocal
set "GAME_DIR=%~dp0.."
set "REPO_ROOT=%GAME_DIR%\..\.."
set "PYTHON=%REPO_ROOT%\.venv\Scripts\python.exe"
set "GAME_EXE=%REPO_ROOT%\SampleGame\build\CampusNPC.exe"

if not exist "%PYTHON%" (
    echo [!] No virtualenv at %PYTHON%
    echo     Create it and install requirements.txt from the repo root first.
    pause
    exit /b 1
)

if not exist "%GAME_EXE%" (
    echo [!] No build at %GAME_EXE%
    echo     Export it from Godot, or run tools\build.bat
    pause
    exit /b 1
)

echo Starting model server...
pushd "%REPO_ROOT%"
start "NPC model server" "%PYTHON%" -m uvicorn backend.gguf_server:app --port 8000
popd

echo Waiting for the server to come up...
REM It builds PDM v2 reference features for all 8 archetypes before serving,
REM so the first health check can take a few seconds.
set /a TRIES=0
:wait
set /a TRIES+=1
if %TRIES% gtr 60 (
    echo [!] Server did not respond after 60s. Launching anyway - NPCs will
    echo     report the connection failure in-game.
    goto launch
)
curl -s -o nul -m 2 http://127.0.0.1:8000/health
if errorlevel 1 (
    timeout /t 1 /nobreak >nul
    goto wait
)
echo Server is up.

:launch
start "" "%GAME_EXE%"
endlocal
